### ISSUE TITLE
Prepare for 2.0 milestone

### ISSUE THREAD

**Issue by Tlaster** [TwidereProject/TwidereX-Android#156]
There're still lots of things that need to be done before 2.0.

- [x] Creating project
- [x] #167
- [ ] Migrating code → #238 
- [ ] Testing

Dependencies that need to be replaced or rewrite
- [x] <del>Jetpack Navigation</del>  → [PreCompose](https://github.com/Tlaster/PreCompose)
- [x] <del>Jetpack ViewModel</del> → [PreCompose](https://github.com/Tlaster/PreCompose)
- [x] <del>Jetpack Paging</del> → paging-common
- [x] <del>Jetpack Room</del> → [SQLDelight](https://github.com/cashapp/sqldelight)
- [x] <del>Jetpack DataStore</del> → datastore-core
- [x] <del>Jetpack WorkManager</del> → [Mamully invoke](https://github.com/TwidereProject/TwidereX-Android/pull/202)

Dependencies that need implementation for JVM
- [x] <del>Exoplayer</del> → [vlcj](https://github.com/caprica/vlcj)
- [ ] Accompanist → [WIP](https://github.com/google/accompanist/issues/552)
- [x] <del>Jetpack Browser</del> → Launch url then handle with deeplink
- [x] <del>Jetpack Exifinterface</del> → [commons-imaging](https://commons.apache.org/proper/commons-imaging/)

Dependencies that might need to reconsider the usage
- Hilt
- Jetpack Startup
